/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SomniaNameService__factory } from "./SomniaNameService__factory";
export { VoucherRedemption__factory } from "./VoucherRedemption__factory";
