/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SomniaNameService } from "./SomniaNameService";
export type { VoucherRedemption } from "./VoucherRedemption";
export * as factories from "./factories";
export { SomniaNameService__factory } from "./factories/SomniaNameService__factory";
export { VoucherRedemption__factory } from "./factories/VoucherRedemption__factory";
